### ISSUE TITLE
novnc

### ISSUE THREAD

**Issue by fe1w0** [tension/ZStack-For-WHMCS-noVNC#1]
请问作者,文章中的vnc是如何添加复制粘贴功能的

**Comment by tension** [comment]
你好，

	    window.sendString = function (str) {
	        f(str.split(""));
	        function f(t) {
	            var character = t.shift();
	            var i=[];
	            var code = character.charCodeAt();
	            var needs_shift = character.match(/[A-Z!@#$%^&*()_+{}:\"<>?~|]/);
	            if (needs_shift) {
	                rfb.sendKey(XK_Shift_L,1);
	            }
	            //rfb.sendKey(code,1);
	            rfb.sendKey(code,0);
	            if (needs_shift) {
	                rfb.sendKey(XK_Shift_L,0);
	            }
	            
	            if (t.length > 0) {
	                setTimeout(function() {f(t);}, 10);
	            }
	        }
	    }
            
        function clipboardClear() {
	        $('#noVNC_clipboard_text').val('');
	        rfb.clipboardPasteFrom("");
	    }
	    
	    function clipboardSend() {
	        const text = $('#noVNC_clipboard_text').val();
	        sendString(text);
	        $('.noVNC_vcenter').toggle();
	        $('#noVNC_clipboard_text').val('');
	    }
	    
	    function clipboardClose() {
	        $('.noVNC_vcenter').toggle();
	    }

**Comment by fe1w0** [comment]
多谢👍
